services:
  mysql1:
    image: mysql:latest
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword1
      MYSQL_DATABASE: database1
    ports:
      - "3307:3306"
    volumes:
      - mysql1_data:/var/lib/mysql

  mysql2:
    image: mysql:latest
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword2
      MYSQL_DATABASE: database2
    ports:
      - "3308:3306"
    volumes:
      - mysql2_data:/var/lib/mysql

  app:
    build: .
    container_name: challenge_app
    environment:
      - PORT=3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql1
      - mysql2

volumes:
  mysql1_data:
  mysql2_data: